# Prism Github - Alacritty
[colors.primary]
background = "#22272e"
foreground = "#d8e0e7"

[colors.cursor]
cursor = "#54aeff"
text = "#22272e"

[colors.selection]
background = "#2d333b"
text = "#d8e0e7"

[colors.normal]
black = "#22272e"
red = "#4793d8"
green = "#65b6ff"
yellow = "#767d86"
blue = "#54aeff"
magenta = "#3f82bf"
cyan = "#76beff"
white = "#d8e0e7"

[colors.bright]
black = "#545d68"
red = "#54aeff"
green = "#76beff"
yellow = "#d8e0e7"
blue = "#6dbaff"
magenta = "#4b9ce5"
cyan = "#87c6ff"
white = "#dbe3e9"
