# Prism Memphis - Alacritty
[colors.primary]
background = "#000000"
foreground = "#d8e0e7"

[colors.cursor]
cursor = "#54aeff"
text = "#000000"

[colors.selection]
background = "#0a0d10"
text = "#d8e0e7"

[colors.normal]
black = "#000000"
red = "#4793d8"
green = "#65b6ff"
yellow = "#616772"
blue = "#54aeff"
magenta = "#3f82bf"
cyan = "#76beff"
white = "#d8e0e7"

[colors.bright]
black = "#3a424f"
red = "#54aeff"
green = "#76beff"
yellow = "#d8e0e7"
blue = "#6dbaff"
magenta = "#4b9ce5"
cyan = "#87c6ff"
white = "#dbe3e9"
