# Prism Nero Marquina - Alacritty
[colors.primary]
background = "#08080a"
foreground = "#e8e4dc"

[colors.cursor]
cursor = "#d4af37"
text = "#08080a"

[colors.selection]
background = "#101014"
text = "#e8e4dc"

[colors.normal]
black = "#08080a"
red = "#b4942e"
green = "#d8b74b"
yellow = "#7b7b86"
blue = "#d4af37"
magenta = "#9f8329"
cyan = "#dcbf5f"
white = "#e8e4dc"

[colors.bright]
black = "#5a5a68"
red = "#d4af37"
green = "#dcbf5f"
yellow = "#e8e4dc"
blue = "#dabb55"
magenta = "#be9d31"
cyan = "#e0c773"
white = "#eae6df"
