# Prism Ocean Depths - Alacritty
[colors.primary]
background = "#0a1018"
foreground = "#d0e0f0"

[colors.cursor]
cursor = "#61e8e1"
text = "#0a1018"

[colors.selection]
background = "#101820"
text = "#d0e0f0"

[colors.normal]
black = "#0a1018"
red = "#52c5bf"
green = "#70eae4"
yellow = "#737f8c"
blue = "#61e8e1"
magenta = "#48aea8"
cyan = "#80ece7"
white = "#d0e0f0"

[colors.bright]
black = "#506070"
red = "#61e8e1"
green = "#80ece7"
yellow = "#d0e0f0"
blue = "#78ebe5"
magenta = "#57d0ca"
cyan = "#90eeea"
white = "#d4e3f1"
